# Site settings
title: SmartHut
email: leonid.v.boykov@gmail.com
description: >-
  Here would be awesome description, but I'm too lasy
  to type it.
baseurl: ""
url: "https://smarthut.github.io"
twitter_username: LeonidBoykov
github_username:  smarthut

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
